### ISSUE TITLE
Undefined variable maxRetryMS in Lambda code

### ISSUE THREAD

**Issue by woodhull** [awslabs/aws-lambda-redshift-loader#200] opened 2019-08-29 19:08 UTC
Perhaps this is an artifact of a previous change that was not cleaned up?

stacktrace:

```
2019-08-29T19:02:17.922Z	588ea97b-1b24-47bd-acb6-39c3ba3b6260	ReferenceError: maxRetryMS is not defined
at Response.<anonymous> (/var/task/index.js:366:81)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:364:18)
```

**Comment by george-viaud** [comment] 2019-09-09 22:04
Same issue here, even if retry time specified, the problem is "why do we get in this err state" in the first place?  Appears that record is status "locked" from our debug which conditional says should not be the case.  Possible race condition?

**Comment by IanMeyers** [comment] 2019-09-10 09:54
Which version of the loader are you using please?

**Comment by IanMeyers** [comment] 2019-09-10 10:16
Nevermind. See that this was introduced in february due to a missing const declaration. Have done an in-place fix of 2.7.0 in dac12be and have distributed to all S3 endpoints. Please redeploy the function or grab it from the release.

**Comment by woodhull** [comment] 2019-09-11 20:03
@IanMeyers  In the future, could you create a new versioned release for eg `2.7.1` if the code has changed?

It seems super confusing that the code that is in a particular version is now different then what was originally published. This also breaks the release notes for the 2.7.0 release on Github, as it appears it only included your new commits from yesterday. 

It's also a pain for us to convince our automated tooling that the code has changed when the version is not changed between releases.

**Comment by woodhull** [comment] 2019-09-11 20:07
Also, if this issue is now fixed should we close this issue?

**Comment by IanMeyers** [comment] 2019-09-12 09:43
@woodhull appreciate your comments and future releases will certainly increment the minor version. However, because this was an egregious bug that rendered 2.7.0 unusable, I felt it important to patch in place, but appreciate the difficulties that this creates. If the issue is fixed then yes please close the issue.

**Closed as completed** 2019-09-12 18:54 UTC
