### ISSUE TITLE
Unable to validate the following destination configurations

### ISSUE THREAD

**Issue by joaolcorreia** [awslabs/aws-lambda-redshift-loader#219] opened 2020-08-17 21:22 UTC
Hi,

My lambda Setup (Only the setup.js) stopped working. It is creating the entry in Dynamo, but not an S3 trigger.

- I set the AWS_REGION on an environment variable
- Run it and get the following error: (I even tried giving Admin permissions to the EC2LambdaSetupRole)
- I didn't change anything on the AWS or setup machine

What could be wrong?

`node setup-file.js ./config/xxxxxxx-data-input/xxxxxx/transactionsfeed.json --region us-west-2
Creating Tables in Dynamo DB if Required
Table LambdaRedshiftProcessedFiles already exists
Table LambdaRedshiftBatches already exists
Table LambdaRedshiftBatchLoadConfig already exists
Creating S3 Event Source for s3://xxxxxx-data-input/xxxxx
Found existing Policy match for S3 path to invoke LambdaRedshiftLoader
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Unable to validate the following destination configurations</Message><ArgumentName1>arn:aws:lambda:us-west-2:xxxxxxxxxx:function:LambdaRedshiftLoader, null</ArgumentName1><ArgumentValue1>Not authorized to invoke function [arn:aws:lambda:us-west-2:xxxxxxxxxxxxxx:function:LambdaRedshiftLoader]</ArgumentValue1><RequestId>390B49F28C754904</RequestId><HostId>q5b9/1BExoq2koB+JdEylVBWoHfcAvbZX9nB7LOU/tKEGc8j7uZMO7CwjCXW4IHLsxfPGuvmQ6E=</HostId></Error>
{ InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-08-17T21:18:04.298Z,
  requestId: '390B49F28C754904',
  extendedRequestId: 'q5b9/1BExoq2koB+JdEylVBWoHfcAvbZX9nB7LOU/tKEGc8j7uZMO7CwjCXW4IHLsxfPGuvmQ6E=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 53.41317189837393 }
{ InvalidArgument: Unable to validate the following destination configurations
    at Request.extractError (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ec2-user/aws-lambda-redshift-loader/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Unable to validate the following destination configurations',
  code: 'InvalidArgument',
  region: null,
  time: 2020-08-17T21:18:04.298Z,
  requestId: '390B49F28C754904',
  extendedRequestId: 'q5b9/1BExoq2koB+JdEylVBWoHfcAvbZX9nB7LOU/tKEGc8j7uZMO7CwjCXW4IHLsxfPGuvmQ6E=',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 53.41317189837393 }`

**Comment by tweng100** [comment] 2021-01-21 17:02
i'm getting the same error. any reason why?

**Comment by IanMeyers** [comment] 2021-01-21 17:37
Yep looks like the Lambda permissions API signature has likely changed in the SDK. Assigning to me and will look tomorrow.

**Comment by tweng100** [comment] 2021-01-21 18:19
@IanMeyers thank you so much for looking into it.

**Comment by IanMeyers** [comment] 2021-01-22 11:07
The issue is happening because we are getting a false positive as to whether the setup believes that S3 can invoke the lambda function. This appears to be because you have other event sources that can also invoke the Lambda, and we are not restricting the check to S3. This is a bug and will be fixed, but if you could please verify via: using the aws-cli and the security principal used to run setup.js, could you please run the following command and paste the output?

`aws lambda get-policy --function-name LambdaRedshiftLoader --output json`

?

Also please obscure any values that you are uncomfortable pasting here (this output will include your AWS Account number).

**Comment by IanMeyers** [comment] 2021-01-22 11:19
Either way - please pull to 373d321 which patches common.js and ensures that these false positives aren't used. This should result in the setup creating a LambdaPermission for each source S3 bucket that you configure as expected.

**Comment by IanMeyers** [comment] 2021-01-22 11:20
Please note that this patch does not require redeployment of the target Lambda function.

**Comment by IanMeyers** [comment] 2021-01-22 11:27
Scratch that - was still too broad a check. Please use version after defb467.

**Closed as completed** 2021-03-11 13:23 UTC
